// <auto-generated />
namespace MundoMascotaRosario.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class unir_Rol_A_Usuario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(unir_Rol_A_Usuario));
        
        string IMigrationMetadata.Id
        {
            get { return "201611290215376_unir_Rol_A_Usuario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
