// <auto-generated />
namespace MundoMascotaRosario.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class se_va_tipo_de_doc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(se_va_tipo_de_doc));
        
        string IMigrationMetadata.Id
        {
            get { return "201611291808241_se_va_tipo_de_doc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
